name: GitHub Actions
on: 
  push:
    branches-ignore:
      -"ga-ignore-*"
  pull_request:
    branches-ignore:
      -"ga-ignore-*"

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-MLH-2-1-chocolatine-thibaut.cousin.git"
  EXECUTABLES: "mysh"
  FICHIER: "coding-style-reports.log"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest 
    steps:
      - name: root
        uses: actions/checkout@v4
      - run: check.sh $(pwd) $(pwd)
      - run: |
          if [ -s $FICHIER ]
          then 
            IFS=$'\n'
            while read line; do echo "::error, line=substring=${line:7:5}::$line"; done < $FICHIER
            exit 1
          else echo "no coding style error"; fi

  check_program_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker
    steps:
      - name: root
        uses: actions/checkout@v4
      - run: make
      - run: make clean
      - run: |
          if [ -x $EXECUTABLES ]; then echo "$EXECUTABLES OK"; else echo "$EXECUTABLES KO" && exit 1; fi

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker
    steps:
      - name: root
        uses: actions/checkout@v4
      - run: make tests_run

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
  